indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: lenta.ru
    - url: https://www.skillbox.ru
      name: Skillbox.ru
    - url: https://www.playback.ru
      name: PlayBack.ru
    - url: https://dombulgakova.ru/
      name: Dombulgakova.ru
    - url: https://volochek.life/
      name: volochek.life

server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true